"""
Shlok artifact helpers.

This module provides thin helpers for creating and updating artifacts
generated by Shlok. It does NOT publish, schedule, or execute anything.

All artifacts created here are drafts and must go through approval flows
handled elsewhere in the system.
"""

from __future__ import annotations

import json
import uuid
from typing import Dict, Optional

from sqlalchemy.orm import Session

from app.models.artifact import Artifact, ArtifactType


def create_post_artifact(
    db: Session,
    workspace_id: str,
    employee_id: str,
    title: str,
    content_text: str,
    content_json: Optional[Dict] = None,
) -> Artifact:
    artifact = Artifact(
        id=str(uuid.uuid4()),
        workspace_id=workspace_id,
        employee_id=employee_id,
        type=ArtifactType.POST,
        title=title,
        content_text=content_text,
        content_json=json.dumps(content_json or {}),
        status="draft",
    )
    db.add(artifact)
    db.commit()
    db.refresh(artifact)
    return artifact


def create_image_artifact(
    db: Session,
    workspace_id: str,
    employee_id: str,
    title: str,
    image_url: str,
    metadata: Optional[Dict] = None,
) -> Artifact:
    artifact = Artifact(
        id=str(uuid.uuid4()),
        workspace_id=workspace_id,
        employee_id=employee_id,
        type=ArtifactType.IMAGE,
        title=title,
        content_text=image_url,
        content_json=json.dumps(metadata or {}),
        status="draft",
    )
    db.add(artifact)
    db.commit()
    db.refresh(artifact)
    return artifact


def create_video_artifact(
    db: Session,
    workspace_id: str,
    employee_id: str,
    title: str,
    notes: str,
    metadata: Optional[Dict] = None,
) -> Artifact:
    artifact = Artifact(
        id=str(uuid.uuid4()),
        workspace_id=workspace_id,
        employee_id=employee_id,
        type=ArtifactType.VIDEO,
        title=title,
        content_text=notes,
        content_json=json.dumps(metadata or {}),
        status="draft",
    )
    db.add(artifact)
    db.commit()
    db.refresh(artifact)
    return artifact


def create_schedule_artifact(
    db: Session,
    workspace_id: str,
    employee_id: str,
    title: str,
    proposed_time: str,
    metadata: Optional[Dict] = None,
) -> Artifact:
    artifact = Artifact(
        id=str(uuid.uuid4()),
        workspace_id=workspace_id,
        employee_id=employee_id,
        type=ArtifactType.SCHEDULE,
        title=title,
        content_text=proposed_time,
        content_json=json.dumps(metadata or {}),
        status="draft",
    )
    db.add(artifact)
    db.commit()
    db.refresh(artifact)
    return artifact
