"""Add triaged_threads

Revision ID: 35d59b173735
Revises: ea96b1fa44ca
Create Date: 2026-02-18 05:13:55.267400

"""
from alembic import op
import sqlalchemy as sa
import app.db_types


# revision identifiers, used by Alembic.
revision = '35d59b173735'
down_revision = 'ea96b1fa44ca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('triaged_threads',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('external_thread_id', sa.String(), nullable=False),
    sa.Column('sender', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('last_received_at', sa.DateTime(), nullable=True),
    sa.Column('last_sent_at', sa.DateTime(), nullable=True),
    sa.Column('followup_due_at', sa.DateTime(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('is_noise', sa.Boolean(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('approval_reason', sa.String(), nullable=True),
    sa.Column('awaiting_reply', sa.Boolean(), nullable=False),
    sa.Column('has_draft', sa.Boolean(), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.String(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('draft_json', app.db_types.SafeJSON(), nullable=True),
    sa.Column('metadata_json', app.db_types.SafeJSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('triaged_threads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_triaged_threads_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_triaged_threads_external_thread_id'), ['external_thread_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_triaged_threads_followup_due_at'), ['followup_due_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_triaged_threads_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_triaged_threads_last_received_at'), ['last_received_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_triaged_threads_last_sent_at'), ['last_sent_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_triaged_threads_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_triaged_threads_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_triaged_threads_workspace_id'), ['workspace_id'], unique=False)

    with op.batch_alter_table('triaged_emails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('previous_category', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('deadline_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('triaged_emails', schema=None) as batch_op:
        batch_op.drop_column('deadline_at')
        batch_op.drop_column('previous_category')

    with op.batch_alter_table('triaged_threads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_triaged_threads_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_triaged_threads_provider'))
        batch_op.drop_index(batch_op.f('ix_triaged_threads_priority'))
        batch_op.drop_index(batch_op.f('ix_triaged_threads_last_sent_at'))
        batch_op.drop_index(batch_op.f('ix_triaged_threads_last_received_at'))
        batch_op.drop_index(batch_op.f('ix_triaged_threads_id'))
        batch_op.drop_index(batch_op.f('ix_triaged_threads_followup_due_at'))
        batch_op.drop_index(batch_op.f('ix_triaged_threads_external_thread_id'))
        batch_op.drop_index(batch_op.f('ix_triaged_threads_category'))

    op.drop_table('triaged_threads')
    # ### end Alembic commands ###
