"""Add onboarding_status

Revision ID: 36fc5403bc75
Revises: 35d59b173735
Create Date: 2026-02-18 05:27:34.927959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36fc5403bc75'
down_revision = '35d59b173735'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.add_column(sa.Column('onboarding_status', sa.String(), nullable=False, server_default='pending'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.drop_column('onboarding_status')

    # ### end Alembic commands ###
