"""Sprint 2 Schema - Final

Revision ID: ea96b1fa44ca
Revises: 003_labeling_preferences_and_read_state
Create Date: 2026-02-18 00:02:41.662888

"""
from alembic import op
import sqlalchemy as sa
import app.db_types


# revision identifiers, used by Alembic.
revision = 'ea96b1fa44ca'
down_revision = '003_labeling_preferences_and_read_state'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.alter_column('action_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('requested_by_user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_approvals_thread_id'), ['thread_id'], unique=False)

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thread_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('provider', sa.String(), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'APPLIED'"))
        batch_op.create_index(batch_op.f('ix_audit_logs_thread_id'), ['thread_id'], unique=False)

    with op.batch_alter_table('drafts', schema=None, naming_convention={
        "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s"
    }) as batch_op:
        batch_op.add_column(sa.Column('intent', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('risk_labels', app.db_types.SafeJSON(), nullable=True))
        batch_op.add_column(sa.Column('missing_info', app.db_types.SafeJSON(), nullable=True))
        batch_op.add_column(sa.Column('version', sa.Integer(), nullable=False, server_default=sa.text('1')))
        batch_op.alter_column('email_message_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_constraint('fk_drafts_email_message_id_email_messages', type_='foreignkey')

    with op.batch_alter_table('meeting_transcripts', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('triaged_emails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requires_approval', sa.Boolean(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('approval_reason', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('awaiting_reply', sa.Boolean(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('last_outbound_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('followup_due_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('followup_snoozed_until', sa.DateTime(), nullable=True))

    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.add_column(sa.Column('style_profile_json', app.db_types.SafeJSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.drop_column('style_profile_json')

    with op.batch_alter_table('triaged_emails', schema=None) as batch_op:
        batch_op.drop_column('followup_snoozed_until')
        batch_op.drop_column('followup_due_at')
        batch_op.drop_column('last_outbound_at')
        batch_op.drop_column('awaiting_reply')
        batch_op.drop_column('approval_reason')
        batch_op.drop_column('requires_approval')

    with op.batch_alter_table('meeting_transcripts', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('drafts', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'email_messages', ['email_message_id'], ['id'])
        batch_op.alter_column('email_message_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('version')
        batch_op.drop_column('missing_info')
        batch_op.drop_column('risk_labels')
        batch_op.drop_column('intent')

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_thread_id'))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'APPLIED'"))
        batch_op.drop_column('provider')
        batch_op.drop_column('thread_id')

    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approvals_thread_id'))
        batch_op.alter_column('requested_by_user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('action_id',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
