"""Sprint 2 Schema - Final

Revision ID: ea96b1fa44ca
Revises: 003_labeling_preferences_and_read_state
Create Date: 2026-02-18 00:02:41.662888

"""
from alembic import op
import sqlalchemy as sa
import app.db_types


# revision identifiers, used by Alembic.
revision = 'ea96b1fa44ca'
down_revision = '003_labeling_prefs'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thread_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('resolved_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('action_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('requested_by_user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_approvals_thread_id'), ['thread_id'], unique=False)

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actor_user_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('target_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('target_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('thread_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('provider', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('before_state', app.db_types.SafeJSON(), nullable=True))
        batch_op.add_column(sa.Column('after_state', app.db_types.SafeJSON(), nullable=True))
        batch_op.add_column(sa.Column('undo_payload', app.db_types.SafeJSON(), nullable=True))
        batch_op.add_column(sa.Column('explain_one_liner', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(), nullable=False, server_default=sa.text("'APPLIED'")))
        batch_op.drop_index('ix_audit_logs_created_at')
        batch_op.drop_index('ix_audit_logs_entity_id')
        batch_op.drop_index('ix_audit_logs_entity_type')
        batch_op.drop_index('ix_audit_logs_user_id')
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_user_id'), ['actor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_thread_id'), ['thread_id'], unique=False)
        batch_op.drop_column('entity_id')
        batch_op.drop_column('entity_type')
        batch_op.drop_column('user_id')
        batch_op.drop_column('changes')

    with op.batch_alter_table('triaged_emails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requires_approval', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('approval_reason', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('awaiting_reply', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('last_outbound_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('followup_due_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('followup_snoozed_until', sa.DateTime(), nullable=True))

    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.add_column(sa.Column('style_profile_json', app.db_types.SafeJSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.drop_column('style_profile_json')

    with op.batch_alter_table('triaged_emails', schema=None) as batch_op:
        batch_op.drop_column('followup_snoozed_until')
        batch_op.drop_column('followup_due_at')
        batch_op.drop_column('last_outbound_at')
        batch_op.drop_column('awaiting_reply')
        batch_op.drop_column('approval_reason')
        batch_op.drop_column('requires_approval')

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('changes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.String(), nullable=False, server_default='system'))
        batch_op.add_column(sa.Column('entity_type', sa.String(), nullable=False, server_default='system'))
        batch_op.add_column(sa.Column('entity_id', sa.String(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_audit_logs_thread_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_user_id'))
        batch_op.create_index('ix_audit_logs_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_audit_logs_entity_type', ['entity_type'], unique=False)
        batch_op.create_index('ix_audit_logs_entity_id', ['entity_id'], unique=False)
        batch_op.create_index('ix_audit_logs_created_at', ['created_at'], unique=False)
        batch_op.drop_column('status')
        batch_op.drop_column('explain_one_liner')
        batch_op.drop_column('undo_payload')
        batch_op.drop_column('after_state')
        batch_op.drop_column('before_state')
        batch_op.drop_column('provider')
        batch_op.drop_column('thread_id')
        batch_op.drop_column('target_id')
        batch_op.drop_column('target_type')
        batch_op.drop_column('actor_user_id')

    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approvals_thread_id'))
        batch_op.alter_column('requested_by_user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('action_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('resolved_at')
        batch_op.drop_column('category')
        batch_op.drop_column('thread_id')

    # ### end Alembic commands ###
